Sa order books
the-difference-engine/spark-start pull request #91
Opened 2017-05-23 00:14 UTC by shaqsinc22

-Books are Now in Order with Newest on Top, Admin Panel Books Index.

2017-05-23 00:15 UTC, Linda-Diamond-Robbins reviewed
You rock Shaeel!

2017-06-05 12:56 UTC, troyleach requested changes

2017-06-05 12:56 UTC, troyleach commented on app/controllers/admin/books_controller.rb
> +  def check_downloads
This looks like new code?
where is the test?

2017-06-05 12:56 UTC, troyleach commented on app/controllers/books_controller.rb
> +    @book.book_downloads += 1
looks like new code...
where is the test?

2017-06-05 12:56 UTC, troyleach commented on app/models/book.rb
> +def check_downloads
looks like new code
where is the test?

2017-06-05 12:56 UTC, troyleach commented on app/views/books/show.html.erb
> +     <% if @book.check_downloads == true %>
check this out...
try this:
```if @book.check_downloads```

2017-06-05 12:56 UTC, troyleach commented on config/routes.rb
> +    # get :download_pdf
what is this?

2017-06-05 12:56 UTC, troyleach commented on db/migrate/20170519012557_change_book_downloads_in_book.rb
> +end
please combine these two migrations
just cleans up the code
(remember rake db:migrate)

2017-06-05 12:56 UTC, troyleach commented on db/schema.rb
>    create_table "categories", force: :cascade do |t|
I up loaded a new book and this is where I got rerouted to

<img width="813" alt="screen shot 2017-05-22 at 7 53 38 pm" src="https://cloud.githubusercontent.com/assets/7662875/26334159/98d56b44-3f28-11e7-8afb-b3db5b90d97d.png">

2017-06-05 17:59 UTC, troyleach requested changes

2017-06-05 17:59 UTC, troyleach commented on app/controllers/books_controller.rb
> +  def download
what are we down loading here? <naming>

2017-06-06 01:08 UTC, merged