Ac sb ux bad urls
the-difference-engine/spark-start pull request #92
Opened 2017-05-23 01:34 UTC by acolletti21

reroutes bad urls to homepage and displays flash message

2017-05-23 01:35 UTC, Linda-Diamond-Robbins reviewed
Thanks!  I think it looks great?

2017-06-05 13:05 UTC, troyleach requested changes
good job other than not writing a test

2017-06-05 13:05 UTC, troyleach commented on app/assets/javascripts/errors.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
can we delete this file?

2017-06-05 13:05 UTC, troyleach commented on app/assets/stylesheets/errors.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
can we delete this file

2017-06-05 13:05 UTC, troyleach commented on app/controllers/errors_controller.rb
> +  end
this looks like new code, where is the test?

2017-06-05 13:05 UTC, troyleach commented on app/controllers/errors_controller.rb
> +  def routing
```routing```
I think we need to name this something different - really doesn't describe what it does

2017-06-05 13:05 UTC, troyleach commented on app/views/layouts/application.html.erb
>      </body>
since we didn't really change anything in this file, can we remove it from the PR

2017-06-05 13:05 UTC, troyleach commented on config/routes.rb
> +
can you please explain to me what is happening here? looks cool

2017-06-05 15:24 UTC, acolletti21 commented on config/routes.rb
> +
The *a is a wildcard that catches any undefined or misspelled route, then uses the routing method in  errors controller to redirect to the home page, and display a flash message saying the page does not exist.

2017-06-05 23:24 UTC, closed without merging